name: Deploy Fullstack App to Vercel

on:
  push:
    branches:
      - master  # Change to your main branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 5: Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          # Add other environment variables here if needed
          # e.g., DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: vercel --prod --token $VERCEL_TOKEN --yes
