name: Deploy Fullstack App to Vercel

on:
  push:
    branches:
      - master  # Change to your main branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Lint code
      - name: Lint
        run: npm run lint

      # Step 5: Build application
      - name: Build
        run: npm run build

      # Step 6: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 7: Set Environment Variables for Production
      - name: Set Vercel Environment Variables
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel env add VITE_AUTH_API_BASE_URL production --value "" --token $VERCEL_TOKEN --yes
          vercel env add VITE_INVENTORY_API_BASE_URL production --value "" --token $VERCEL_TOKEN --yes
          vercel env add VITE_API_BASE_URL production --value "" --token $VERCEL_TOKEN --yes

      # Step 8: Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token $VERCEL_TOKEN --yes
